pipeline {
  agent any

  options { timestamps() }

  stages {
    stage('Notify: pending') {
      steps {
        githubNotify context: 'ci/jenkins-lab2', status: 'PENDING', description: 'Lab2 started'
      }
    }

    stage('Lab2 test: always fail') {
      steps {
        sh 'exit 1'
      }
    }
  }

  post {
    success {
      githubNotify context: 'ci/jenkins-lab2', status: 'SUCCESS', description: 'Lab2 passed'
    }
    failure {
      githubNotify context: 'ci/jenkins-lab2', status: 'FAILURE', description: 'Lab2 faile'
    }
    aborted {
      githubNotify context: 'ci/jenkins-lab2', status: 'ERROR', description: 'Lab2 aborted'
    }
  }
}